---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-web
  name: app-web
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-web
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
        - name: app-web
          image: {{ .Values.werf.image.myapp }}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: svc-web
  namespace: prod
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector:
    app: app-web
#  type: LoadBalancer